### PR TITLE
Disable `numba` for code coverage

### LINKED ISSUE #1079: Disable Numba for code coverage
Numba decorated functions are decreasing the overall code coverage of our package.

### PR DESCRIPTION
**Pull request by philipc2**
Closes #1079 

## Overview

- Sets the `NUMBA_DISABLE_JIT: 1` environment variable to disable Numba when running tests for code coverage

### CODE REVIEW

**Comment by rajeeja** [comment]
This would increase the tests runtime substantially, we might go over the free alloted runtime by GitHub actions runners. 
I know this is useful and have done it often during the development cycle, we can think of another solution; but why disable it permanently?

**Comment by philipc2** [comment]
> This would increase the tests runtime substantially, we might go over the free alloted runtime by GitHub actions runners. I know this is useful and have done it often during the development cycle, we can think of another solution; but why disable it permanently?

This is a great point. I'll disable it **_only_** for the code coverage tests.

**Review by rajeeja — CHANGES_REQUESTED** [review]
How about similar change in a few other places:? 
```

./grid/coordinates.py:import math
./grid/coordinates.py:    lon = math.atan2(y, x)
./grid/coordinates.py:    lat = math.asin(z)
./grid/coordinates.py:    lon = math.atan2(y, x)
./grid/coordinates.py:    lat = math.asin(z)
./grid/coordinates.py:    lon = math.atan2(y, x)
./grid/coordinates.py:    lat = math.asin(z)
```

**Comment by philipc2** [comment]
> How about similar change in a few other places:?
> 
> ```
> 
> ./grid/coordinates.py:import math
> ./grid/coordinates.py:    lon = math.atan2(y, x)
> ./grid/coordinates.py:    lat = math.asin(z)
> ./grid/coordinates.py:    lon = math.atan2(y, x)
> ./grid/coordinates.py:    lat = math.asin(z)
> ./grid/coordinates.py:    lon = math.atan2(y, x)
> ./grid/coordinates.py:    lat = math.asin(z)
> ```

These should all be address.

**Comment by rajeeja** [comment]
> > How about similar change in a few other places:?
> > ```
> > 
> > ./grid/coordinates.py:import math
> > ./grid/coordinates.py:    lon = math.atan2(y, x)
> > ./grid/coordinates.py:    lat = math.asin(z)
> > ./grid/coordinates.py:    lon = math.atan2(y, x)
> > ./grid/coordinates.py:    lat = math.asin(z)
> > ./grid/coordinates.py:    lon = math.atan2(y, x)
> > ./grid/coordinates.py:    lat = math.asin(z)
> > ```
> 
> These should all be addressed.

Here or another PR?

**Comment by philipc2** [comment]
> > > How about similar change in a few other places:?
> > > ```
> > > 
> > > ./grid/coordinates.py:import math
> > > ./grid/coordinates.py:    lon = math.atan2(y, x)
> > > ./grid/coordinates.py:    lat = math.asin(z)
> > > ./grid/coordinates.py:    lon = math.atan2(y, x)
> > > ./grid/coordinates.py:    lat = math.asin(z)
> > > ./grid/coordinates.py:    lon = math.atan2(y, x)
> > > ./grid/coordinates.py:    lat = math.asin(z)
> > > ```
> > 
> > 
> > These should all be addressed.
> 
> Here or another PR?

The changes are in this PR, unless I am missing something.

**Review by rajeeja — APPROVED** [review]

**Pull request merged**
