### PR TITLE
Coordinates conversion helpers overloads

### LINKED ISSUE #346: Support `Numpy.ndArray` for Node 2D/3D Coordinate Conversion Functions
**Describe the feature you'd like added to this project**
Enable `node_xyz_to_lonlat_rad`, `node_lonlat_rad_to_xyz`, `normalize_in_place` take `np.array()` as input and output

**Link to original functionality implementation elsewhere, if applicable**
Originigaly:
1. It only takes `list` as input and the output is also `list`
**Links to other examples, if applicable**

**Describe the solution you'd like**
Modify the current `node_xyz_to_lonlat_rad`, `node_lonlat_rad_to_xyz`, `normalize_in_place` helper functions
such that: 1. it takes `np.array()` or `list` as input. 2. The output is in the `np.array()` format

**Additional context**

### PR DESCRIPTION
**Pull request by hongyuchen1030**
Closes #346 

## Overview
Enable `node_xyz_to_lonlat_rad`, `node_lonlat_rad_to_xyz`, `normalize_in_place` take `np.array()` as input and output

Modify the current node_xyz_to_lonlat_rad, node_lonlat_rad_to_xyz, normalize_in_place helper functions
such that: 1. it takes np.array() or list as input. 2. The output is in the np.array() format
## Note:
Disable the numba `@njit` for all `helpers.py` since numba doesn't support the `isinstance` function

### CODE REVIEW

**Comment by philipc2** [comment]
Did you mean to have the base branch of this PR to be the multi precision coordinate one?

**Comment by hongyuchen1030** [comment]
> Did you mean to have the base branch of this PR to be the multi precision coordinate one?

Yes, the coordinates function are going to be overloaded with `mpfr` data type eventually

**Comment by hongyuchen1030** [comment]
> Did you mean to have the base branch of this PR to be the multi precision coordinate one?

Yes, the coordinates function are going to be overloaded with `mpfr` data type eventually

**Comment by philipc2** [comment]
> > Did you mean to have the base branch of this PR to be the multi precision coordinate one?
> 
> Yes, the coordinates function are going to be overloaded with `mpfr` data type eventually

Considering my comment in #339, we should start with adding this feature for fixed-arithmetic, since it would be beneficial to have before merging all the multi-precision work.

**Comment by hongyuchen1030** [comment]
> > > Did you mean to have the base branch of this PR to be the multi precision coordinate one?
> > 
> > 
> > Yes, the coordinates function are going to be overloaded with `mpfr` data type eventually
> 
> Considering my comment in #339, we should start with adding this feature for fixed-arithmetic, since it would be beneficial to have before merging all the multi-precision work.

That works for me. As I mentioned before, my job is to deliver a working function here, and I am open to any developing modification later.

**Comment by rajeeja** [comment]
> ## Note:
> Disable the numba `@njit` for all `helpers.py` since numba doesn't support the `isinstance` function

We can use `type` `ducking type` or `Union type` (python 3.10+) instead of `isinstance` they are supported by numba.

**Comment by hongyuchen1030** [comment]
> > ## Note:
> > Disable the numba `@njit` for all `helpers.py` since numba doesn't support the `isinstance` function
> 
> We can use `type` `ducking type` or `Union type` (python 3.10+) instead of `isinstance` they are supported by numba.

sounds good. I will leave my implemented algorithm in the multi-precision branch. And feel free to adapt to any better delivery codes

**Comment by philipc2** [comment]
@hongyuchen1030 

I have changed the base of this branch to point towards `multi_precision` instead of `main`

**Comment by hongyuchen1030** [comment]
> @hongyuchen1030
> 
> I have changed the base of this branch to point towards `multi_precision` instead of `main`

Thank you very much!

@aaronzedwick Can you help merge the redesign into this branch and merge it into the `multi_precision` branch please?

**Comment by aaronzedwick** [comment]
@hongyuchen1030 I tried merging everything, but I am a bit confused about how to do it since this is your own fork. Should I check out your fork, and merge the main branch from the fork into this branch from the fork? And then push into your branch? Or is there some other way?

**Comment by aaronzedwick** [comment]
I got everything merged into your branch, do you want me to push it directly?

**Comment by hongyuchen1030** [comment]
@aaronzedwick This branch shouldn't be considered as `multiprecision` since it just overloads the normal coordinate conversion with the `numpy.array()` and it should be merged into main

**Pull request closed without merging**
