### PR TITLE
Multiprecision unique coords detection through verts

### PR DESCRIPTION
**Pull request by hongyuchen1030**
Finish the 1st step of #318 
**Data Read in**
- [x] Support multi-precision when initializing through `Grid.__from_vert__()`

## Overview

This will convert every user input coordinates to the user-specified precision `gmpy2.mpfr` types. It can recognize two coordinates even though they're extremely closed up to any `gmpy2` supported precision. To achieve the precision higher than python`float` (53 bits), it's highly recommended that users use the string as input. This PR also introduce new constant for multi-precision usage:
1. `INT_FILL_VALUE_MPZ`: The filled value that represented by the `gmpy2.mpz` type, the value will be the same as `INT_FILL_VALUE`
2. `FLOAT_PRECISION_BITS`: 53, the python`float` precision bits

For more information about the multi-precision and exact computation paradigm, please refers to the following materials
[GMPY2](https://gmpy2.readthedocs.io/en/latest/index.html)
[The Exact Computation Paradigm](https://www.cgal.org/exact.html)

## Expected Usage

```Python
import uxarray as ux

# Provide nodes that are extremely closed to each other
face_nodes_connectivity = [['1.000000000000000000', '1.000000000000000000001', '1.0000000000000000000012'],
 ['1.000000000000000001', '1.000000000000000000002', '1.0000000000000000000013']]

uxgrid =   ux.Grid(face_nodes_connectivity, multi_precision=True, precision= 65,
                        vertices=True,
                        islatlon=False,
                        concave=False)
print(uxgrid.nMesh2_face )# It will still detect two faces without degenration
>>> 2

# Perform any provided grid manipulation and then the results is precise up the the 65 bits
```

## PR Checklist

**General**
- [x] An issue is linked created and linked
- [x] Add appropriate labels
- [x] Filled out Overview and Expected Usage (if applicable) sections

**Testing**
- [x] Adequate tests are created if there is new functionality
- [x] Tests cover all possible logical paths in your function
- [x] Tests are not too basic (such as simply calling a function and nothing else)

**Documentation**
- [x] Docstrings have been added to all new functions
- [x] Docstrings have updated with any function changes
- [x] Internal functions have a preceding underscore (`_`) and have been added to `docs/internal_api/index.rst`
- [x] User functions have been added to `docs/user_api/index.rst`

**Examples**
- [x] Any new notebook examples added to `docs/examples/` folder
- [x] Clear the output of all cells before committing
- [x] New notebook files added to `docs/examples.rst` toctree
- [x] New notebook files added to new entry in `docs/gallery.yml` with appropriate thumbnail photo in `docs/_static/thumbnails/`

### CODE REVIEW

**Comment by hongyuchen1030** [comment]
@philipc2 @anissa111 
The pre-commit keeps failing after I added the jupyter notebook example `example/004-multiprecision-usage.ipynb`

Can you help me to take a look into that? Thanks

**Comment by philipc2** [comment]
> @philipc2 @anissa111 The pre-commit keeps failing after I added the jupyter notebook example `example/004-multiprecision-usage.ipynb`
> 
> Can you help me to take a look into that? Thanks

I will take a look at this Monday

**Comment by philipc2** [comment]
> > First thing I've noticed is that you've pushed commits for all of the usage examples, not just the one you created. The changes are minor (PyCharm related metadata), but in the future try to avoid pushing all changes.
> 
> I think that's the reason why the pre-commit fail. But how should I avoid that from happening? I didn't modify any other examples here. I just created my own example, and ran the `pre-commit`. On my end it showed that no pre-commit fix are committed to my github (mine and other examples)

This is workflow when working:
1. Make any code changes 
2. Run `pre-commit run --all-files`
3. Only add specific files that I want to include in the PR (avoid `git add-A`). Sometimes when you run a notebook, it'll change the meta data or include the output, so when you do `git add -A`, it'll include those changes
4. I have it set up to where pre-commit runs when I attempt to commit changes, this should run our tests and if anything fails, you will need to re add the changes (step 3). However if you do step 2 before 3, this one is not necessary
5. Push to your branch

**Comment by hongyuchen1030** [comment]
> > > First thing I've noticed is that you've pushed commits for all of the usage examples, not just the one you created. The changes are minor (PyCharm related metadata), but in the future try to avoid pushing all changes.
> > 
> > 
> > I think that's the reason why the pre-commit fail. But how should I avoid that from happening? I didn't modify any other examples here. I just created my own example, and ran the `pre-commit`. On my end it showed that no pre-commit fix are committed to my github (mine and other examples)
> 
> This is workflow when working:
> 
> 1. Make any code changes
> 2. Run `pre-commit run --all-files`
> 3. Only add specific files that I want to include in the PR (avoid `git add-A`). Sometimes when you run a notebook, it'll change the meta data or include the output, so when you do `git add -A`, it'll include those changes
> 4. I have it set up to where pre-commit runs when I attempt to commit changes, this should run our tests and if anything fails, you will need to re add the changes (step 3). However if you do step 2 before 3, this one is not necessary
> 5. Push to your branch

got it, thanks!

**Comment by anissa111** [comment]
Hey! I wanted to drop in real quick before spending additional time on a longer review that currently it doesn't look like your example notebook is working on the preview build: https://uxarray--321.org.readthedocs.build/en/321/examples/004-multiprecision-usage.html

**Comment by hongyuchen1030** [comment]
> Hey! I wanted to drop in real quick before spending additional time on a longer review that currently it doesn't look like your example notebook is working on the preview build: https://uxarray--321.org.readthedocs.build/en/321/examples/004-multiprecision-usage.html

It has some commit issue when I created the notebook. But thanks to @philipc2 the issue is fixed and I will correct the notebook today later. Thanks!

**Comment by rajeeja** [comment]
From 53 to 60 bit precision is that so necessary to use another library for this gain

**Comment by hongyuchen1030** [comment]
> From 53 to 60 bit precision - is that necessary to use another library for this gain?

Thank you for your comment, and I appreciate your concern. Here is why it is necessary to incorporate multi-precision support:

The Python float type is limited to 53 bits of precision, which means we can't go beyond that using standard libraries. By integrating gmpy2, designed for multi-precision arithmetic, we can surpass the 53-bit limit and achieve higher precision.

While the PR mentions a precision increase to 60 bits, multi-precision support allows for arbitrary precision settings. We can choose any desired value, such as 100 bits or 200 bits, depending on project requirements. The 60-bit example is just illustrative.

Enabling multi-precision support facilitates not only higher precision calculations but also exact computation. The exact computation is crucial in computational geometry to ensure precise and accurate results, especially when rounding errors and numerical instability could impact the outcome.

Enabling multi-precision support not only allows for higher precision calculations but also provides the capability for exact computation. Exact computation is an important paradigm in computational geometry as it ensures precise and accurate results, particularly in cases where rounding errors and numerical instability can affect the outcome.

Incorporating multi-precision support isn't just about adding another package. It means embracing the exact computation paradigm, providing robust analysis for both the geoscience and computational geometry communities. For more details, please refer to issue #318 .

**Comment by philipc2** [comment]
> 



> > From 53 to 60 bit precision - is that necessary to use another library for this gain?
> 
> Thank you for your comment, and I appreciate your concern. Here is why it is necessary to incorporate multi-precision support:
> 
> The Python float type is limited to 53 bits of precision, which means we can't go beyond that using standard libraries. By integrating gmpy2, designed for multi-precision arithmetic, we can surpass the 53-bit limit and achieve higher precision.
> 
> While the PR mentions a precision increase to 60 bits as an example, multi-precision support allows for arbitrary precision settings. We can choose any desired value, such as 100 bits or 200 bits, depending on project requirements. The 60-bit example is just illustrative.
> 
> Enabling multi-precision support facilitates not only higher precision calculations but also exact computation. The exact computation is crucial in computational geometry to ensure precise and accurate results, especially when rounding errors and numerical instability could impact the outcome.
> 
> Enabling multi-precision support not only allows for higher precision calculations but also provides the capability for exact computation. Exact computation is an important paradigm in computational geometry as it ensures precise and accurate results, particularly in cases where rounding errors and numerical instability can affect the outcome.
> 
> Incorporating multi-precision support isn't just about adding another package. It means embracing the exact computation paradigm, providing robust analysis for both the geoscience and computational geometry communities. For more details, please refer to issue #318 .

I agree with everything here. There will be plenty of other applications for this beyond just what is implemented here. I think as long as these packages don't conflict with our current and future (Datashader, Shapely, etc) dependencies, I think it's a great addition.

**Comment by rljacob** [comment]
Can you say a little more about how this will be used in practice?  Normally everything in Uxarray will be in default python precision but sometimes a calculation will have to be done in increased precision?  How do we decide and what has to happen to "convert" to using this library?

**Comment by hongyuchen1030** [comment]
> Can you say a little more about how this will be used in practice? Normally everything in Uxarray will be in default python precision but sometimes a calculation will have to be done in increased precision? How do we decide and what has to happen to "convert" to using this library?

So by default, our UXArray project uses the python `float` for all calculations. But if users want to achieve the arbitrary-precision, they can set the `multi-precision` flag as `True` and the desired precision when initializing the Grid object. Then all operations in the UXarray will be done with the desired precision.

```python
float_grid = ux.Grid(verts) # The default floating point Grid object

multi_precision_grid = ux.Grid(verts, multiprecision=True, precision=100)# The multiplrecision Grid object that's set to the 100 precision
```

With this feature, we can achieve
1. The unique coordinate determination: We can distinguish two coordinates even though they're extremely close to each other
2. The exact intersection points between GCRs or GCR and constant latitude
3. We can also achieve exact computations of conservative zonal re-gridding


For detailed information, you can also refer to the following link 
1. [Multi-Precision User Example](https://uxarray--321.org.readthedocs.build/en/321/examples/004-multiprecision-usage.html)
2. #318

**Comment by philipc2** [comment]
> > Can you say a little more about how this will be used in practice? Normally everything in Uxarray will be in default python precision but sometimes a calculation will have to be done in increased precision? How do we decide and what has to happen to "convert" to using this library?
> 
> So by default, our UXArray project uses the python `float` for all calculations. But if users want to achieve the arbitrary-precision, they can set the `multi-precision` flag as `True` and the desired precision when initializing the Grid object. Then all operations in the UXarray will be done with the desired precision.
> 
> ```python
> # The default floating point Grid object
> float_grid = ux.Grid(verts) 
> 
> # The multiplrecision Grid object that's set to the 100 precision
> multi_precision_grid = ux.Grid(verts, multiprecision=True, precision=100)
> ```
> 
> In other words, we never mix the usage of multi-precision and the python `float`, if the grid object is set to default `float` operation, all the operations will be in floating points. If the grid object is set to multiprecision, then all operation will be in arbitray-precision. And we can always round the multiprecision number back to the `float` precision with different rounding options
> 
> With this feature, we can achieve
> 
> 1. The unique coordinate determination: We can distinguish two coordinates even though they're extremely close to each other
> 2. The exact intersection points between GCRs or GCR and constant latitude
> 3. We can also achieve exact computations of conservative zonal re-gridding
> 
> For detailed information, you can also refer to the following link
> 
> 1. [Multi-Precision User Example](https://uxarray--321.org.readthedocs.build/en/321/examples/004-multiprecision-usage.html)
> 2. [Incorporating GMPY2 for multiple precision calculation #318](https://github.com/UXARRAY/uxarray/issues/318)

Other than initializing a grid from vertices, what other applications would there be for this? I'm personally not very experienced with multiprecision arithmetic, so if you could point me to any good papers / references, that would be much appreciated!

**Comment by hongyuchen1030** [comment]
> > > Can you say a little more about how this will be used in practice? Normally everything in Uxarray will be in default python precision but sometimes a calculation will have to be done in increased precision? How do we decide and what has to happen to "convert" to using this library?
> > 
> > 
> > So by default, our UXArray project uses the python `float` for all calculations. But if users want to achieve the arbitrary-precision, they can set the `multi-precision` flag as `True` and the desired precision when initializing the Grid object. Then all operations in the UXarray will be done with the desired precision.
> > ```python
> > # The default floating point Grid object
> > float_grid = ux.Grid(verts) 
> > 
> > # The multiplrecision Grid object that's set to the 100 precision
> > multi_precision_grid = ux.Grid(verts, multiprecision=True, precision=100)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In other words, we never mix the usage of multi-precision and the python `float`, if the grid object is set to default `float` operation, all the operations will be in floating points. If the grid object is set to multiprecision, then all operation will be in arbitray-precision. And we can always round the multiprecision number back to the `float` precision with different rounding options
> > With this feature, we can achieve
> > 
> > 1. The unique coordinate determination: We can distinguish two coordinates even though they're extremely close to each other
> > 2. The exact intersection points between GCRs or GCR and constant latitude
> > 3. We can also achieve exact computations of conservative zonal re-gridding
> > 
> > For detailed information, you can also refer to the following link
> > 
> > 1. [Multi-Precision User Example](https://uxarray--321.org.readthedocs.build/en/321/examples/004-multiprecision-usage.html)
> > 2. [Incorporating GMPY2 for multiple precision calculation #318](https://github.com/UXARRAY/uxarray/issues/318)
> 
> Other than initializing a grid from vertices, what other applications would there be for this? I'm personally not very experienced with multiprecision arithmetic, so if you could point me to any good papers / references, that would be much appreciated!

Thank you for your interest. The exact computation is the subject that we can never bypass in the computational geometry
This will also be my thesis direction. 

The application of the exact computation of the [https://www.cgal.org/exact.html](https://www.cgal.org/exact.html) will be not only useful in determining unique coordinates but also in
1. Determining is a point really on that GCR? (What if it just 1.0e-20 magnitude away from the GCR?). A single point doesn't seems important here, but what if there'are 200000 points that each one of it is 1.0e-20 from the last one? The error will accumulate

When dealing with large datasets, even small errors can accumulate and lead to significant discrepancies. Using exact computation can help ensure that each point is accurately placed on the GCR.


2. Get the exact intersection point between two GCRs: Are you sure such an intersection point is exactly on both GCRs. not just 1.0e-20 away from the 1st GCR? And if I calculate this point from the 1st GCR, it will yield the exact same result as when I calculate it from the 2nd GCR?

Without exact computation, it's possible that the intersection point may be off by a small margin, which can cause issues in certain applications. By using exact computation, you can be sure that the intersection point is exactly on both GCRs and that the same result will be obtained regardless of which GCR is used to calculate it.

If you're interested, you can also refer to the following:
1. [Adaptive Precision Floating-Point Arithmetic
and Fast Robust Geometric Predicates](https://people.eecs.berkeley.edu/~jrs/papers/robustr.pdf)
[Precision and robustness in geometric computations](https://link.springer.com/chapter/10.1007/3-540-63818-0_9)

**Comment by rljacob** [comment]
> So by default, our UXArray project uses the python float for all calculations. But if users want to achieve the arbitrary-precision, they can set the multi-precision flag as True and the desired precision when initializing the Grid object. Then all operations in the UXarray will be done with the desired precision.

Thanks that is very helpful.  What happens if you want to do an operation between two grids, like an intersection, and one is default precision and one is arbitrary?

I'm also concerned about performance.  Do operations on grid declared with arbitrary precision take a lot more time?

**Comment by hongyuchen1030** [comment]
> > So by default, our UXArray project uses the python float for all calculations. But if users want to achieve the arbitrary-precision, they can set the multi-precision flag as True and the desired precision when initializing the Grid object. Then all operations in the UXarray will be done with the desired precision.
> 
> Thanks that is very helpful. What happens if you want to do an operation between two grids, like an intersection, and one is default precision and one is arbitrary?
> 
> I'm also concerned about performance. Do operations on grid declared with arbitrary precision take a lot more time?

1. I don't think the current UXarray supports the "Intersection between two Grid objects" so far. But if we plan to do than in the futures, we can give users two options: make both arbitrary-precision(catch up to the current arbitrary precision) or round both down to the floating points

2. Yes, the arbitrary precision will take a longer time. However, as I mentioned before, the `float` operation never mixed with the arbitrary precision, which means the performance of the current float point operation will remain unchanged. 

I have tested the performance difference on the coordinates conversion so far, and here're the results summary:

Using the `gmpy2` library, precision can be increased by 2 to 3 orders of magnitude compared to the standard `float64` type. This significant improvement in precision comes at the cost of only 1 to 2 orders of magnitude increase in runtime.

**Review by philipc2 — COMMENTED** [review]
Hi Hongyu,

I won't be able provide a detailed review until sometime next week when I start full time, however I have a couple comments I'd like to share:
* Given that this is related to your masters dissertation, I think that Uxarray would be a fantastic canvas for you to implement and test many of your algorithms & ideas
* We have to keep in mind that we will primarily still be working with standard Python datatypes for most implementations
* I would suggest keeping the multi-precision implementation separated from our standard `Grid` class for readability. We still need to discuss the exact design that we will move forward with, but one idea would be to create a multiprecision `Grid` class that would be specifically written for what you have here. 

Overall though, I think this work is extremely fascinating and I'm excited to dig deeper into it soon!

**Comment by hongyuchen1030** [comment]
> Hi Hongyu,
> 
> I won't be able provide a detailed review until sometime next week when I start full time, however I have a couple comments I'd like to share:
> 
> * Given that this is related to your masters dissertation, I think that Uxarray would be a fantastic canvas for you to implement and test many of your algorithms & ideas
> * We have to keep in mind that we will primarily still be working with standard Python datatypes for most implementations
> * I would suggest keeping the multi-precision implementation separated from our standard `Grid` class for readability and code flow. We still need to discuss the exact design that we will move forward with, but one idea would be to create a multiprecision `Grid` class that would be specifically written for what you have here.
> 
> Overall though, I think this work is extremely fascinating and I'm excited to dig deeper into it soon!

Hi Philip,

Thank you so much for your reply and concerns. We discussed the computation provision at our last meeting and agreed to give more thought to how to present it in our project.  And that when you do the review, please don't worry too much about the implementation and algorithm, just focus on the project structures design and APIs.

Thank you for your effort, and we would appreciate hearing your valuable advice when you start full-time.

**Comment by hongyuchen1030** [comment]
Hi @aaronzedwick , I read your commit message. 

Please never push directly to any branch because it might break the CI. 

As mentioned in Slack, please create a new branch from my branch `hongyuchen1030/multiprecision_unique_coords_detection_through_verts`, you can name it as `multiprecision_unique_coords_detection_through_ds` or any other name you want. Put your implementation there and then create a Pull Request. And we can start from there.

I will revert your commit from this PR so as to pass the CI. Please let me know if you have any problem

**Comment by aaronzedwick** [comment]
@hongyuchen1030 Sorry about that! I made a new branch and attempted to push and and make a new PR, but I believe you have to add additional permissions. I assume you want me to push to your forked branch. Let me know, thanks for the help! I got this message:
"To https://github.com/hongyuchen1030/uxarray.git
 ! [remote rejected] multiprecision_unique_coords_detection_through_ds -> multiprecision_unique_coords_detection_through_ds (permission denied)
error: failed to push some refs to 'https://github.com/hongyuchen1030/uxarray.git'"

**Comment by hongyuchen1030** [comment]
> @hongyuchen1030 Sorry about that! I made a new branch and attempted to push and and make a new PR, but I believe you have to add additional permissions. I assume you want me to push to your forked branch. Let me know, thanks for the help! I got this message: "To https://github.com/hongyuchen1030/uxarray.git ! [remote rejected] multiprecision_unique_coords_detection_through_ds -> multiprecision_unique_coords_detection_through_ds (permission denied) error: failed to push some refs to 'https://github.com/hongyuchen1030/uxarray.git'"

All your implementation are going to stay in **YOUR** repository. What we are gonna do here is, you're going to create a new branch from `hongyuchen1030/multiprecision_unique_coords_detection_through_verts` in your repository and do your implementation. And once you done developing, commit & push it to **YOUR** repository

I just tested it on my side:
I created a new branch from your `aaronzedwick/version_method` branch, do some work, and push to my own repo called [`hongyuchen1030:test_new_branch_on_Hongyu_end`]((https://github.com/hongyuchen1030/uxarray/tree/test_new_branch_on_Hongyu_end)). You should be able to see it on my fork as well.

**Comment by aaronzedwick** [comment]
@hongyuchen1030 Thanks for all the help, I made my own repo and made a branch like you said. You should be able to see all the changes on https://github.com/aaronzedwick/uxarray/tree/multiprecision_unique_coords_detection_through_ds If you need me to change or do anything else just message me on slack.

**Comment by hongyuchen1030** [comment]
> @hongyuchen1030
> 
> While we figure our and work out an adequate design for releasing multi-precision support, I've created a protected branch `multi_precision` that you can make PR's to instead of directly to `main`
> 
> This should also allow future PR's, like the ones @aaronzedwick is working on to use `multi_precision` as a base and then make changes to then push back into `multi_precision`.
> 
> We will also have a PR similar to the ongoing Redesign one that will be the one that merges into `main` once it is ready.
> 
> Let me know if this works and if I can clarify anything! Hopefully this speeds up development,

Thank you very much for your help! That works for me!

**Comment by philipc2** [comment]
> > @hongyuchen1030
> > While we figure our and work out an adequate design for releasing multi-precision support, I've created a protected branch `multi_precision` that you can make PR's to instead of directly to `main`
> > This should also allow future PR's, like the ones @aaronzedwick is working on to use `multi_precision` as a base and then make changes to then push back into `multi_precision`.
> > We will also have a PR similar to the ongoing Redesign one that will be the one that merges into `main` once it is ready.
> > Let me know if this works and if I can clarify anything! Hopefully this speeds up development,
> 
> Thank you very much for your help! That works for me!

Fantastic! I'll start reviewing it now, since there won't be much pressure on making it ready for main just yet.

**Comment by hongyuchen1030** [comment]
Hi @aaronzedwick, can you help me figure out the readthedoc issue and merge this PR into the [UXARRAY:multi_precision](https://github.com/UXARRAY/uxarray/tree/multi_precision) branch? Thanks

**Review by philipc2 — COMMENTED** [review]
@hongyuchen1030 

There appears to be an issue with the Area Calculation notebook. I'll look into it.

**Comment by aaronzedwick** [comment]
My ds branch also failed the readthedocs previously. Could be for the same reason, let me know if you figure anything out, I don't know much about how the check works.

**Comment by hongyuchen1030** [comment]
Hi @philipc2, Do you have any idea in mind about why the read-doc fails and how to fix it?

**Comment by aaronzedwick** [comment]
@hongyuchen1030 If we can get this branch merged it will make it easier to merge other branches, like my from_ds function. Right now the multi-precision branch doesn't have any of the multi-precision helpers or functions. Getting this merged would add those to the branch.

**Review by philipc2 — APPROVED** [review]
Approving tentatively to speed up development, with a detailed review expected when `multi_precision` is merged into `man`

**Pull request merged**
