### PR TITLE
Add the brand new (beta) GitHub hosted M1 runner into ci.yml

### PR DESCRIPTION
**Pull request by erogluorhan**
Add "macos-14" to CI matrix for M1 testing

## Overview
GitHub just [announced](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/) their brand new M1 runner, "macos-14",  for use. Let us give it a try in our CI actions.

See this PR's own action runs for a quick demo of it.

### CODE REVIEW

**Comment by rajeeja** [comment]
this is nice, I use M1:) 
do they charge or count hours towards it?
the last i checked they were free for linux and some hour limit appled to anything windows or mac.

**Comment by erogluorhan** [comment]
No, they don't charge. It is available to open source, just like the other GH-hosted runners such as "macos-latest". Though, it's in beta. Currently our tests failed with it, I didn't dig into it to see if it was our code or their runner's fault. I use an M2 :)

**Comment by kafitzgerald** [comment]
It looks like this is the problem: https://github.com/UXARRAY/uxarray/actions/runs/7734670366/job/21089077449?pr=685#step:4:12

The default must work fine for the current options, but obviously not w/ arm64

https://github.com/conda-incubator/setup-miniconda?tab=readme-ov-file#example-11-alternative-architectures

**Comment by kafitzgerald** [comment]
Well, that was false hope, but it looks like there's a workaround in [this thread](https://github.com/conda-incubator/setup-miniconda/issues/312) and work in progress to support this.

**Comment by erogluorhan** [comment]
> Well, that was false hope, but it looks like there's a workaround in [this thread](https://github.com/conda-incubator/setup-miniconda/issues/312) and work in progress to support this.

Thanks a lot for pointing this out! It helped us overcome the architecture issue. Now is a shell issue I believe, which leads to `python` command not being recognized. On it!

**Comment by erogluorhan** [comment]
Yay, we got them all to pass! 

Any ideas on cleaning up the X64 vs. ARM64 conditioning in the file a further bit would be appreciated.

**Comment by kafitzgerald** [comment]
> Yay, we got them all to pass!
> 
> Any ideas on cleaning up a bit the X64 vs. ARM64 conditioning for the "conda setup" step in the file would be appreciated.

I think this might be the best we can do right now (open to ideas though).  I did [something similar over on geocat-viz](https://github.com/NCAR/geocat-viz/pull/194/files).

I'm hopeful that once setup-miniconda actually has support for this it'll look a bit cleaner. There's a PR in review now to add it.

**Pull request merged**
