### PR TITLE
Read UGRID files with transposed connectivity (i.e. fesom.mesh.diag)

### LINKED ISSUE #282: FESOM grid connectivity stored as tranpose
The dimension of `Mesh2_face_nodes` is `(3 x nFace)` instead of `(nFace x 3)`

From the UGRID Conventions:

> The face_dimension attribute specifies which netcdf dimension is used to indicate the index of the face in the connectivity arrays. This is needed because some applications store the data with the fastest varying index first, and some with that index last. The default is to use the num_faces as fastest dimension; e.g. a (num_faces, 3) array for triangles, but some applications might use a (3, num_faces) order, in which case the face_dimension attribute is required to help the client code disambiguate. The edge_dimension attribute is similar for the edge connectivity arrays.

### PR DESCRIPTION
**Pull request by philipc2**
Closes #282 #1026

## Overview

* Updates UGRID reader to correctly parse grid files that contain transposed connectivity information
  *  The `fesom.mesh.diag.nc` grid file stores connectivity information in a transpose order (`[3, n_face]` instead of `[n_face, 3]`
* Fixes a bug where the start index was not correctly adjusted due to a negative fill value. 

## Plot of `fesom.mesh.diag.nc`

image

### CODE REVIEW

**Review by rajeeja — APPROVED** [review]
Good fix, FESOM stores elements each node is connected to aka adjacency and happy to see that we had the diag file in main for over a year. It wasn't tested.
test/grid_geoflow.exo is removed ? It shouldn't have been there in the first place. Anyways. I'll approve as this will enable newer changes.

**Comment by philipc2** [comment]
> Good fix, FESOM stores elements each node is connected to aka adjacency and happy to see that we had the diag file in main for over a year. It wasn't tested. test/grid_geoflow.exo is removed ? It shouldn't have been there in the first place. Anyways. I'll approve as this will enable newer changes.

Yeah, one of our testing scrips produces the `.exo` file and it must of been included in a previous commit.

**Comment by rajeeja** [comment]
> > Good fix, FESOM stores elements each node is connected to aka adjacency and happy to see that we had the diag file in main for over a year. It wasn't tested. test/grid_geoflow.exo is removed ? It shouldn't have been there in the first place. Anyways. I'll approve as this will enable newer changes.
> 
> Yeah, one of our testing scrips produces the `.exo` file and it must of been included in a previous commit.

One minor thing that could make it good would be to have something about *transpose* in the [README](https://github.com/UXARRAY/uxarray/blob/main/test/meshfiles/ugrid/fesom/README.md)

**Comment by philipc2** [comment]
> > > Good fix, FESOM stores elements each node is connected to aka adjacency and happy to see that we had the diag file in main for over a year. It wasn't tested. test/grid_geoflow.exo is removed ? It shouldn't have been there in the first place. Anyways. I'll approve as this will enable newer changes.
> > 
> > 
> > Yeah, one of our testing scrips produces the `.exo` file and it must of been included in a previous commit.
> 
> One minor thing that could make it good would be to have something about _transpose_ in the [README](https://github.com/UXARRAY/uxarray/blob/main/test/meshfiles/ugrid/fesom/README.md)

Good idea. I'll add a note to it.

**Review by aaronzedwick — APPROVED** [review]

**Comment by philipc2** [comment]
@fluidnumerics-joe 

I'm not sure if you've seen this PR, but we've already added and released support for reading the UGRID-compliant FESOM grid files.

I haven't followed up with #1013 since merging this. However, I'll work on getting it in soon.

**Comment by philipc2** [comment]
> Sounds good. I haven't been able to get uxarray working for fesom2 netcdf grids from the latest pypi release, but I can from your philipc2/fesom branch. Curious to know the timeline to have these features in the pypi index .

I'm going to wrap up #1013 this week and aim to release it next week.

**Pull request merged**
