### PR TITLE
CITATION.cff: Remove duplicate entries, add Rachel, add lacking ORCID IDs

### PR DESCRIPTION
**Pull request by erogluorhan**
Simple changes to 
- remove a duplicate author entry
- add Amber and Rachel
- add ORCID IDs for multiple folks

### CODE REVIEW

**Review by philipc2 — APPROVED** [review]

**Comment by erogluorhan** [comment]
@philipc2 per our UXarray meeting today, folks will provide me with their ORCID IDs, and I will add them here

**Comment by erogluorhan** [comment]
@philipc2 @rajeeja This is now ready for review.
@aaronzedwick feel free to add your ORCID with a commit or let me know it and I can add.

**Review by philipc2 — APPROVED** [review]
Everything looks good to me!

**Comment by aaronzedwick** [comment]
> @philipc2 @rajeeja This is now ready for review. @aaronzedwick feel free to add your ORCID with a commit or let me know it and I can add.

My ID is 0000-0003-3229-3381. Thanks!

**Review by apliberty — APPROVED** [review]

**Review by aaronzedwick — APPROVED** [review]
Sorry ignore that last review, I was signed into my school account briefly and forgot to sign out.

**Pull request merged**
