### PR TITLE
`Grid.from_points()` with Spherical Delaunay & Voronoi 

### PR DESCRIPTION
**Pull request by philipc2**
## Overview

* Implements the `Grid.from_points()` class method which is used to construct grid connectivity from unstructured grid points
  *  Spherical Voronoi Regions 
  * Spherical Delaunay Triangulation
* Implements multiple descriptor variables for assistance with grid diagnostics
  *  `Grid.triangular`
  * `Grid.partial_sphere_coverage`
  * `Grid.global_sphere_coverage`
  * `Grid.boundary_node_indices`
  * `Grid.boundary_face_indices`
* Implements two new grid plotting routines
* `Grid.plot.face_area_distrubtion()`
* `Grid.plot.face_degree_distribution()`

## User Guide

User guide notebook showcasing how to construct a grid from points consider the various types of distributions that are possible (global, global with holes, regional, and regional with holes)
- Rendered notebook [here ](https://uxarray--1023.org.readthedocs.build/en/1023/user-guide/from-points.html)

### CODE REVIEW

**Comment by aaronzedwick** [comment]
What needs to be done here in order to get it ready for review?

**Comment by philipc2** [comment]
> What needs to be done here in order to get it ready for review?

I am wrapping up the implementation and documentation today. Will be requesting reviews after. 

We should start looking at regional triangulation using projections, like what you were doing in #442 

I'll be populating the sub-issues n #349 today as well. Will assign and update you accordingly.

**Comment by aaronzedwick** [comment]
> > What needs to be done here in order to get it ready for review?
> 
> I am wrapping up the implementation and documentation today. Will be requesting reviews after.
> 
> We should start looking at regional triangulation using projections, like what you were doing in #442
> 
> I'll be populating the sub-issues n #349 today as well. Will assign and update you accordingly.

Awesome! It looks good to me so far.

What do you mean by regional triangulation?

**Comment by philipc2** [comment]
> > > What needs to be done here in order to get it ready for review?
> > 
> > 
> > I am wrapping up the implementation and documentation today. Will be requesting reviews after.
> > We should start looking at regional triangulation using projections, like what you were doing in #442
> > I'll be populating the sub-issues n #349 today as well. Will assign and update you accordingly.
> 
> Awesome! It looks good to me so far.
> 
> What do you mean by regional triangulation?

Spherical triangulation works great for data that is distributed across the sphere. If we have regional patches of data (think a subset over some arbitrary region), performing a spherical triangulation will produce extremely large triangles along the border of the region. In this case, we'd want to investigate using a planar triangulation on a projection (i.e. sterographic) like you were doing in #442

**Comment by aaronzedwick** [comment]
Gotcha that makes sense, thanks for explaining!

**Comment by aaronzedwick** [comment]
Is this ready for review now?

**Comment by philipc2** [comment]
> Is this ready for review now?

Yes

**Review by rajeeja — APPROVED** [review]
This is good foundational work, we can specify laplacian smoothing etc. as a follow up PR.

**Comment by rajeeja** [comment]
Did some more digging - `pys2geometry ` and `healpy` it might be worth exploring these also at somepoint. I'll put an issue about it.

**Comment by philipc2** [comment]
> Did some more digging - `pys2geometry ` and `healpy` it might be worth exploring these also at somepoint. I'll put an issue about it.

`healpy` is relevant to #1028

**Review by aaronzedwick — APPROVED** [review]
Looks great, I will finish the regional delaunay part hopefully next week and get that added in as well. Just fix the merge conflicts and it's good to go!

**Pull request merged**
