### PR TITLE
Add Ruff to Pre-Commit Hooks

### LINKED ISSUE #576: Use Ruff instead of YAPF in Pre-Commit
### Proposed new feature or change:

Ruff is significantly faster (> 100x) and more comprehensive that YAPF, and is used commonly by other packages.

### PR DESCRIPTION
**Pull request by philipc2**
Closes #576 

# Overview
- Replaces `YAPF` linting with `ruff`, which is significantly faster & more comprehensive 
- Changes throughout to adhere to `ruff` linting

### CODE REVIEW

**Review by rajeeja — COMMENTED** [review]
this touches a lot of things, we are going away from `style google?`

CI fails? These are just formatting commits?

**Comment by philipc2** [comment]
> this touches a lot of things, we are going away from `style google?`

`ruff` has a larger set of rules & checks that it runs compared to `YAPF`. I belie it follows closer to the `PEP` standards, which personally is preferred. 

> CI fails? These are just formatting commits?

Working on fixing it, had an import break.

**Comment by rajeeja** [comment]
Any articles or references to why one is preferred over the other?

**Comment by philipc2** [comment]
> Any articles or references to why one is preferred over the other?

The formatter for `ruff` closely follows Black, a good comparison between it and Google's can be found [here](https://safjan.com/black-vs-yapf/)

**Comment by philipc2** [comment]
@erogluorhan 

I've resolved the merge conflicts.

**Review by erogluorhan — APPROVED** [review]
I like it better

**Review by rajeeja — APPROVED** [review]
this makes the readability better, thanks!

**Pull request merged**
