### PR TITLE
Convert Uxarray API document into markdown

### PR DESCRIPTION
**Pull request by erogluorhan**
This draft PR adds our UXarray API document in Google Drive to ` docs/user_api/uxarray_api.md` for easier sharing and discussion purposes.

There might be slight improvements to this PR before review/merge.

See the [rendered markdown file](https://github.com/UXARRAY/uxarray/blob/api_md/docs/user_api/uxarray_api.md).

### CODE REVIEW

**Review by clyne — APPROVED** [review]
Looks like it is ready for public comment to me.

**Review by anissa111 — APPROVED** [review]

**Review by michaelavs — APPROVED** [review]

**Comment by clyne** [comment]
@erogluorhan should we merge this and share it with our stakeholders, or would you like to get input from Colin and Brian?

**Comment by erogluorhan** [comment]
> @erogluorhan should we merge this and share it with our stakeholders, or would you like to get input from Colin and Brian?

Merged! Let us share it with our stakeholders and improve it with the feedback!

**Comment by clyne** [comment]
Cool! Where is the rendered documentation available from?

**Comment by erogluorhan** [comment]
> Cool! Where is the rendered documentation available from?

Here it is: https://github.com/UXARRAY/uxarray/blob/main/docs/user_api/uxarray_api.md

We can also link it from the Raijin website, too.

**Comment by clyne** [comment]
Thanks. But I think the real confusing part is that if you go to the UXarray repo, the README has a link to documentation, which takes you [here](https://uxarray.readthedocs.io/en/latest/). But clicking on "user API" takes you to a blank page.

**Comment by erogluorhan** [comment]
> Thanks. But I think the real confusing part is that if you go to the UXarray repo, the README has a link to documentation, which takes you [here](https://uxarray.readthedocs.io/en/latest/). But clicking on "user API" takes you to a blank page.

Oh, I see now; great catch! The RTD pages are supposed to be automatically populating when there is actual function implementation in the code base. Since there is no implementation for now, all the three pages under RTD website (API reference, User API, and Internal API) are shown as blank pages. To fix this and avoid confusion, I created the new PR #16 where I put a little explanation paragraph that forwards the reader to our tentative API documentation in markdown (https://github.com/UXARRAY/uxarray/blob/main/docs/user_api/uxarray_api.md).

**Pull request merged**
