### PR TITLE
Optimize `point_within_gca` by Eliminating Redundant Lat/Lon Conversions

### LINKED ISSUE #936: Performance Issue: Unnecessary Re-conversion of Coordinates in `point_within_gca`
### Proposed new feature or change:

The current implementation of point_within_gca unnecessarily re-converts lat/lon coordinates from Cartesian coordinates, which negatively impacts performance.

The following lines re-compute lat/lon from Cartesian coordinates:

python
```
GCRv0_lonlat = np.array(
        _xyz_to_lonlat_rad_no_norm(gca_cart[0][0], gca_cart[0][1], gca_cart[0][2])
    )
GCRv1_lonlat = np.array(
    _xyz_to_lonlat_rad_no_norm(gca_cart[1][0], gca_cart[1][1], gca_cart[1][2])
)
```

However, Uxarray already stores lat/lon coordinates, which can be passed directly to avoid redundant computation. This approach reduces both time and space complexity while aligning better with the overall architecture.

Proposed Solution:

- Pass the existing lat/lon coordinates directly to eliminate the unnecessary conversion.
- Update upstream function calls to `point_within_gca`

### PR DESCRIPTION
**Pull request by amberchen122**
Closes #936

## Overview
This PR addresses a performance issue in the `point_within_gca `function, which unnecessarily re-converted lat/lon coordinates from Cartesian coordinates. Since Uxarray already stores lat/lon coordinates, they can be passed directly to avoid redundant computation. This change reduces time and space complexity while better aligning with the architecture.

### Proposed changes:

- [ ] Root cause: change [`point_within_gca`](https://github.com/UXARRAY/uxarray/blob/82e46b8c79bb0107753398ddab096c5f6eb9b718/uxarray/grid/arcs.py#L127) to accept lat_lon coordinates
- [ ] Upsteam functions that called `point_within_gca`:
    - [x] [`gca_gca_intersection`](https://github.com/UXARRAY/uxarray/blob/82e46b8c79bb0107753398ddab096c5f6eb9b718/uxarray/grid/intersections.py#L12C5-L12C25)
    - [x] [`gca_constLat_intersection`](https://github.com/UXARRAY/uxarray/blob/82e46b8c79bb0107753398ddab096c5f6eb9b718/uxarray/grid/arcs.py#L127)

    - [x] [`_populate_face_latlon_bound`](https://github.com/UXARRAY/uxarray/blob/82e46b8c79bb0107753398ddab096c5f6eb9b718/uxarray/grid/geometry.py#L663)
    - [ ] test files

## PR Checklist

**General**
- [x] An issue is linked created and linked
- [x] Add appropriate labels
- [x] Filled out Overview and Expected Usage (if applicable) sections

**Testing**
- [ ] Adequate tests are created if there is new functionality
- [ ] Tests cover all possible logical paths in your function
- [ ] Tests are not too basic (such as simply calling a function and nothing else)

**Documentation**
- [ ] Docstrings have been added to all new functions
- [ ] Docstrings have updated with any function changes
- [ ] Internal functions have a preceding underscore (`_`) and have been added to `docs/internal_api/index.rst`
- [ ] User functions have been added to `docs/user_api/index.rst`

**Examples**
- [ ] Any new notebook examples added to `docs/examples/` folder
- [ ] Clear the output of all cells before committing
- [ ] New notebook files added to `docs/examples.rst` toctree
- [ ] New notebook files added to new entry in `docs/gallery.yml` with appropriate thumbnail photo in `docs/_static/thumbnails/`

### CODE REVIEW

**Comment by amberchen122** [comment]
@philipc2 As we discussed in today's meeting, could you please suggest the new function API/signature for [point_within_gca](https://github.com/UXARRAY/uxarray/blob/82e46b8c79bb0107753398ddab096c5f6eb9b718/uxarray/grid/arcs.py#L127)? 

I will then proceed with changing the function bodies :)

**Comment by philipc2** [comment]
Hi @amberchen122 

This is one of the main sections we'd need to update:

https://github.com/UXARRAY/uxarray/blob/82e46b8c79bb0107753398ddab096c5f6eb9b718/uxarray/grid/arcs.py#L170-L177

We should update the helper functions to take in both the Cartesian and LatLon versions of each point/gca. This may look like the following:
```Python
point_within_gca(pt_cart, pt_latlon_rad, gca_cart, gca_latlon_rad, is_directed=False)
```

In addition to this PR, I will look into getting #878 finished this week, which will ensure that the coordinates will always be normalized. I'll request a review from you once this is prepared.

**Comment by philipc2** [comment]
I'd like to also mention that we should try to avoid as many conversions between `np.ndarray` and `list` as possible. This could be something to considering when optimizing.

**Comment by hongyuchen1030** [comment]
@amberchen122 To answer your question
https://github.com/UXARRAY/uxarray/blob/85748f17064502598838fb6ba929d4395150780e/uxarray/grid/intersections.py#L13

1. When the function is meant to calculate the scalar values, `gca1_cart : [1, 3] ， gca2_cart: [1, 3]`, where gca1 and gca2 mean the two vertices of the GCR respectively. And I was trying this function vectorizable, which means if `gca1_cart : [n, 3] ， gca2_cart: [n, 3]`then it should be able to calculate n intersection point at the same time . (I forgot if the current implementation met that goal yet)
2. Don't delete the `fma` flag, it might be very useful in the future

**Comment by amberchen122** [comment]
> @amberchen122 To answer your question
> 
> https://github.com/UXARRAY/uxarray/blob/85748f17064502598838fb6ba929d4395150780e/uxarray/grid/intersections.py#L13
> 
> 1. When the function is meant to calculate the scalar values, `gca1_cart : [1, 3] ， gca2_cart: [1, 3]`, where gca1 and gca2 mean the two vertices of the GCR respectively. And I was trying this function vectorizable, which means if `gca1_cart : [n, 3] ， gca2_cart: [n, 3]`then it should be able to calculate n intersection point at the same time . (I forgot if the current implementation met that goal yet)
> 2. Don't delete the `fma` flag, it might be very useful in the future

Thank you for the clarification! 
1. The current `gca_gca_intersection` implementation is not vectorized yet. Therefore, it currently only deals with  `gca1_cart : [1, 3] ， gca2_cart: [1, 3]` inputs. 
2. The current `gca_gca_intersection` implementation is not utilizing the fma flag.

For this PR, would it be ok for me to update the function docstring to reflect what they are currently implementing? I will put a note in the comment about the modified parts(gca dimension, and fma flag) for future reference.

**Comment by hongyuchen1030** [comment]
> > @amberchen122 To answer your question
> > https://github.com/UXARRAY/uxarray/blob/85748f17064502598838fb6ba929d4395150780e/uxarray/grid/intersections.py#L13
> > 
> > 
> > 1. When the function is meant to calculate the scalar values, `gca1_cart : [1, 3] ， gca2_cart: [1, 3]`, where gca1 and gca2 mean the two vertices of the GCR respectively. And I was trying this function vectorizable, which means if `gca1_cart : [n, 3] ， gca2_cart: [n, 3]`then it should be able to calculate n intersection point at the same time . (I forgot if the current implementation met that goal yet)
> > 2. Don't delete the `fma` flag, it might be very useful in the future
> 
> Thank you for the clarification!
> 
> 1. The current `gca_gca_intersection` implementation is not vectorized yet. Therefore, it currently only deals with  `gca1_cart : [1, 3] ， gca2_cart: [1, 3]` inputs.
> 2. The current `gca_gca_intersection` implementation is not utilizing the fma flag.
> 
> For this PR, would it be ok for me to update the function docstring to reflect what they are currently implementing? I will put a note in the comment about the modified parts(gca dimension, and fma flag) for future reference.

sounds good! Yeah always keep the docstring updated with the current implementaton

**Comment by philipc2** [comment]
Closing this because of #1072

**Pull request closed without merging**
