### PR TITLE
Multiprecision coordinates conversion

### PR DESCRIPTION
**Pull request by hongyuchen1030**
Finish the 2st step of #318 

**Grid Pre-processing**
- [x] Precise spherical and cartesian coordinates conversion

### CODE REVIEW

**Comment by hongyuchen1030** [comment]
@aaronzedwick Can you also help me merge the redesign into this branch as well? Thank you very much.

**Comment by philipc2** [comment]
@hongyuchen1030 

I'd suggest merging `multiprecision_unique_coords_detection_through_verts` into this branch instead since we already updated that one to account for the redesign.

**Comment by hongyuchen1030** [comment]
> @hongyuchen1030
> 
> I'd suggest merging `multiprecision_unique_coords_detection_through_verts` into this branch instead since we already updated that one to account for the redesign.

Got it. Thank you very much for your help. @aaronzedwick , can you help me work with this as well? Thank you very much

**Comment by aaronzedwick** [comment]
I can try and help, I have actually been having some trouble merging my from_ds branch with the redesign as well. Once I get some time I will try and see if I can get that done and hopefully, I will have learned how to from that.

**Comment by philipc2** [comment]
@hongyuchen1030 

Considering the work in #748, should we close this pull request and consider re-visiting this in the future. 

At some point, I'd like to check in on the general state of multiprecision support. There have been a lot of changes to the structure of our tool since that last time we looked at it. 

There also isn't an issue directly related to the implementation here. Would you mind creating one when you have some time.

**Comment by hongyuchen1030** [comment]
> @hongyuchen1030
> 
> Considering the work in #748, should we close this pull request and consider re-visiting this in the future.
> 
> At some point, I'd like to check in on the general state of multiprecision support. There have been a lot of changes to the structure of our tool since that last time we looked at it.
> 
> There also isn't an issue directly related to the implementation here. Would you mind creating one when you have some time.

Thanks for your information. We can just close it at this point.

**Pull request closed without merging**
