### PR TITLE
Documentation Improvements

### PR DESCRIPTION
**Pull request by philipc2**
# Overview

Extensive overhaul to our documentation, with significant organizational and quality-of-life changes.

## [Updated User Guide](https://uxarray--810.org.readthedocs.build/en/810/userguide.html)
New Sections:
- Plotting
- Advanced Plotting Techniques
- Subsetting
- Compatibility with HoloViz Tools

Added descriptions to each section on the landing page.

## [Updated Example Gallery ](https://uxarray--810.org.readthedocs.build/en/810/gallery.html)

New categories:
- Visualization Examples
- Workflow Examples
- External Examples

Most of the "Usage Examples" have been migrated into the "User Guide" section.

### CODE REVIEW

**Comment by philipc2** [comment]
@rytam2 @aaronzedwick 

This PR should be ready for some initial feedback, especially regarding the new organization.

**Review by rajeeja — CHANGES_REQUESTED** [review]
how about removing 005- etc. numbering from the notebooks?

**Comment by philipc2** [comment]
> how about removing 005- etc. numbering from the notebooks?

Good suggestion. Done

**Review by aaronzedwick — APPROVED** [review]
This looks really good Philip! Definitely a great improvement!

**Comment by rytam2** [comment]
All content looks awesome Philip! Added a couple comments on minor edits but looks good to merge otherwise.

**Pull request merged**
