### PR TITLE
Fix and Improve Upstream CI

### LINKED ISSUE #521: Upstream CI Failing
Due to missing dependencies after recent visualization PR merges.

### LINKED ISSUE #648: Improve upstream CI
### Proposed new feature or change:

Incorporate common upstream CI practices from packages like Xarray into here, i.e.:

- Get rid of `ci/upstream-dev-environment.yml` and use `ci/environment.yml` also for upstream testing purposes
- Add `ci/install-upstream.sh` that handles
  -  Removal of conda-installed upstream packages
  - Installation of these packages as follows:
    - scipy nightly wheel packages    
    - scientific-python nightly wheel packages
    - rest of the packages from source
- Update `upstream-dev-ci` workflow to 
   - Incorporate the above changes
   - Switch from miniconda to micromamba

### PR DESCRIPTION
**Pull request by erogluorhan**
Closes #521.
Closes #648 (See details of the issue regarding implementations here).

See a successful run of [Upstream CI](https://github.com/UXARRAY/uxarray/actions/runs/7465427979) workflow.

## PR Checklist

**General**
- [x] An issue is linked created and linked
- [x] Add appropriate labels

### CODE REVIEW

**Review by rajeeja — APPROVED** [review]
All checks have passed, look good and cleaner with the new `install-upstream.sh` script

**Review by philipc2 — APPROVED** [review]
Looks great!

**Comment by philipc2** [comment]
@erogluorhan 

Prior to merging, let's wait for the action to finish running. It appears to be running unexpectedly long.

**Review by aaronzedwick — APPROVED** [review]
Looks good to me! I like the new improvements

**Pull request merged**
