### PR TITLE
o Remove duplicate test - test_build_nNodes_per_face

### PR DESCRIPTION
**Pull request by rajeeja**
## TestConnectivity Change

```Python
Remove test_build_nNodes_per_face and keep the version with more checks (verts)

```

## PR Checklist

**General**
- [ ] An issue is linked created and linked
- [ ] Add appropriate labels
- [ x] Filled out Overview and Expected Usage (if applicable) sections

**Testing**
- [ ] Adequate tests are created if there is new functionality
- [x ] Tests cover all possible logical paths in your function
- [ ] Tests are not too basic (such as simply calling a function and nothing else)

### CODE REVIEW

**Review by philipc2 — APPROVED** [review]
Good catch!

**Review by aaronzedwick — APPROVED** [review]
Looks good!

**Comment by rajeeja** [comment]
@philipc2 Any ideas on why [this windows test](https://github.com/UXARRAY/uxarray/actions/runs/5581053332/jobs/10198780210?pr=383#step:7:98) was cancelled ?

**Comment by philipc2** [comment]
> @philipc2 Any ideas on why [this windows test](https://github.com/UXARRAY/uxarray/actions/runs/5581053332/jobs/10198780210?pr=383#step:7:98) was cancelled ?

This is strange, looks like the timed out on windows (at least for 3.10 and 3.11). Looking into it.

**Pull request merged**
