### PR TITLE
User Guide & Documentation Improvements 

### LINKED ISSUE #473: Set up User Guide section in Documentation

### PR DESCRIPTION
**Pull request by philipc2**
Closes #473 

## Overview

- Introduces a the [User Guide](https://uxarray--472.org.readthedocs.build/en/472/userguide.html) section to our documentation
- Updated the front page with new descriptions and references to the Contributors Guide and User Guide

## Updated Front Page
image

### CODE REVIEW

**Comment by philipc2** [comment]
@aaronzedwick 

Rajeev and I are working on populating a User Guide. I've assigned two sections to you if you'd be interested in helping out with them! 

We can provide some guidance & a template as well!

**Comment by aaronzedwick** [comment]
> @aaronzedwick
> 
> Rajeev and I are working on populating a User Guide. I've assigned two sections to you if you'd be interested in helping out with them!
> 
> We can provide some guidance & a template as well!

I would love to help! Templates and any guidance would be greatly appreciated! Also some insight into what is meant by distance operations? The great circle arcs?

**Comment by philipc2** [comment]
> > @aaronzedwick
> > Rajeev and I are working on populating a User Guide. I've assigned two sections to you if you'd be interested in helping out with them!
> > We can provide some guidance & a template as well!
> 
> I would love to help! Templates and any guidance would be greatly appreciated! Also some insight into what is meant by distance operations? The great circle arcs?

It would discuss the KDTree and BallTree data structures, including distance metrics. We could talk about the great circle arcs also (since haversine distance metric considers the lines as arcs)

**Review by hongyuchen1030 — COMMENTED** [review]
good work! I wonder if we can add some pictures as illustrations in the User Guid/Terminology section?

Also some introduction for our constants will be helpful as well

**Comment by rajeeja** [comment]
> Also some introduction for our constants will be helpful as well

constants intro is more of a subject for the developers guide

**Comment by hongyuchen1030** [comment]
> > Also some introduction for our constants will be helpful as well
> 
> constants intro is more of a subject for the developers guide

There are still some useful constants for the users.

For example, when the users are using our package, knowing what's the smallest value for the relative error tolerance is also important.

**Pull request merged**
