### PR TITLE
Doc Cleanup

### LINKED ISSUE #641: Organize Internal API
### Proposed new feature or change:

Break internal API  to manageable and readable chunks. Add a little more to the purpose of each subsection.

### PR DESCRIPTION
**Pull request by philipc2**
Closes #641 #884 #743 #407

## Overview

* Refactored API reference to be better aligned with similar packages, such as `xarray`
* Corrected the order of sections in the User Guide toctree
* Updated the README
* Updated docstrings 
* Fixed typos in some user guide sections

[Rendered Documentation with Changes](https://uxarray--977.org.readthedocs.build/en/977/)

### CODE REVIEW

**Comment by philipc2** [comment]
@erogluorhan @rajeeja 

Thoughts on removing the "Internal" and "User" API split that we've been employing since the start of the package? The only benefit of having an internal API on our documentation would be for developers. 

Xarray doesn't provide an internal API. 

https://docs.xarray.dev/en/stable/api.html

**Comment by rajeeja** [comment]
Just yesterday I had a discussion with @rljacob 

Yes, we should remove that distinction. There are a few changes I have in mind for cleaning up the Docs. I will also contribute to the pr.

**Comment by philipc2** [comment]
> Just yesterday I had a discussion with @rljacob
> 
> Yes, we should remove that distinction. There are a few changes I have in mind for cleaning up the Docs. I will also contribute to the pr.

Sounds great! Feel free to discuss anything here. We could hop on a call and/or work on some together next week also.

**Comment by erogluorhan** [comment]
Sounds good to me

**Comment by philipc2** [comment]
@rajeeja @erogluorhan @aaronzedwick 

This should be ready for review now. There's a good chance I've probably missed something (especially in the API reference). I'm also open to any other improvements that either of you may suggest!

**Comment by rajeeja** [comment]
https://uxarray--977.org.readthedocs.build/en/977/internal_api/generated/uxarray.UxDataArray.html#uxarray.UxDataArray.__init__

only difference and gradient have links. 

gradient examples isn't formatted right: https://uxarray--977.org.readthedocs.build/en/977/generated/uxarray.UxDataArray.gradient.html#uxarray.UxDataArray.gradient

**Comment by philipc2** [comment]
> https://uxarray--977.org.readthedocs.build/en/977/internal_api/generated/uxarray.UxDataArray.html#uxarray.UxDataArray.__init__
> 
> only difference and gradient have links.
> 
> gradient examples isn't formatted right: https://uxarray--977.org.readthedocs.build/en/977/generated/uxarray.UxDataArray.gradient.html#uxarray.UxDataArray.gradient

Good catches!

**Review by rajeeja — APPROVED** [review]

**Comment by aaronzedwick** [comment]
image
A lot of functions (as you can see in the image) have `(...[,...])` or simply `[...]`. What is it meant to symbolize? That it takes arguments? Looks a  little strange to me.

**Comment by rytam2** [comment]
<p>I am thinking a bit more on the <code>Grid</code> section, as this section may be accessed more by folks since UXarray is developed for unstructured grids:  </p><ul><li>Perhaps changing the subheading like <code>Constructor</code> to <code>Creating a Grid/UxDataArray/UxDataSet</code> would be more intuitive? </li><li>Also would making <code>Coordinate Attributes</code> as a single subheading, and have <code>spherical coordinates</code> and <code>cartesian coordinates</code> a sub-subheading be a good idea? </li><li>Suggest moving <code>Descriptors</code> following right after <code>Dimensions</code> for more intuitive understanding in case people reading API from top-down, instead of being in between the coordinates section and connectivity. </li><li>Suggest adding unit for <code>Grid.edge_node_distances</code> and <code>Grid.edge_face_distances</code></li></ul>

**Comment by philipc2** [comment]
Thanks for the comments @rytam2 !


> Perhaps changing the subheading like `Constructor` to `Creating a Grid/UxDataArray/UxDataSet` would be more intuitive?

The constructor isn't intended for direct construction, as that is what the class methods and API functions are for. 

> * Also would making `Coordinate Attributes` as a single subheading, and have `spherical coordinates` and `cartesian coordinates` a sub-subheading be a good idea?

This might introduce too many sub-headers. 

> * Suggest moving `Descriptors` following right after `Dimensions` for more intuitive understanding in case people reading API from top-down, instead of being in between the coordinates section and connectivity.

Right now the order is:
* Dimensions
* Coordinates
* Connectivity
* Descriptors

Do you mean moving it before the coordinates?

> * Suggest adding unit for `Grid.edge_node_distances` and `Grid.edge_face_distances`

Good idea! Will add this

**Comment by rytam2** [comment]
>The constructor isn't intended for direct construction, as that is what the class methods and API functions are for.

Got it; just wondering is there another term for constructor? It's fine too if there isn't. 

> This might introduce too many sub-headers.

Fair, I think we can keep it as is.  

> Do you mean moving it before the coordinates?

Yes!

**Pull request merged**
